"""Package file for views."""
from .product import Products
from .register import register_user
from .register import login_user
from .product_type import ProductTypes
from .product import Products
from .customer import Customers
from .order import Orders
from .order_products import OrderProducts
from .payment_type import PaymentTypes
